CREATE TABLE MENUS(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR NOT NULL,
PARENT_ID INTEGER,
POSITION INTEGER NOT NULL
);

CREATE TABLE CONTENTS (
ID INTEGER PRIMARY KEY NOT NULL,
CONTENT VARCHAR NOT NULL,
CONTENT_TYPE VARCHAR NOT NULL, --title, image, text, etc
MENU_ID INTEGER NOT NULL,
POSITION INTEGER --Discribe the position of contents under a menu article
);

CREATE TABLE 