CREATE TABLE MENUS(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR NOT NULL,
PARENT_ID INTEGER,
POSITION INTEGER NOT NULL
);

CREATE TABLE ARTICLES (
ID INTEGER PRIMARY KEY NOT NULL,
TITLE VARCHAR NOT NULL,
CONTENT VARCHAR NOT NULL,
MENU_ID INTEGER NOT NULL
);

CREATE TABLE PARAMS (
KEY VARCHAR PRIMARY KEY NOT NULL,
VALUE VARCHAR
);
