/*Parent menu id reserved to 20*/
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (1, '关于我们', 0);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (2, '写在前面的话', 1);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (3, '编者按', 2);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (4, '常用链接', 3);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (5, '常见缩写', 4);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (6, '第一章 学前准备', 5);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (7, '第二章 学术', 6);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (8, '第三章 生活', 7);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (9, '第四章 工作', 8);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (10, '历代版本前言', 9);
INSERT INTO MENUS(ID, NAME, POSITION) VALUES (11, '特别鸣谢', 10);
/*Parent menus in Chapter 2*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (12, '2.1 Major 专业介绍', 7, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (13, '2.2 HUA 人文与艺术', 7, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (14, '2.7 IQP & MQP', 7, 7);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (15, '2.8 转学分', 7, 8);
/*Parent menus in Chapter 3*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (16, '3.1 校园生活', 8, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (17, '3.2 日常生活', 8, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (18, '3.3 居住', 8, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (19, 'reserved', 0, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION) VALUES (20, 'reserved', 0, 0);

/*Fill up Chapter 1*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (21, '1.1 签证', 6, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (22, '1.2 机票', 6, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (23, '1.3 行李', 6, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (24, '1.4 随身衣物', 6, 3);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (25, '1.5 日常用品 ', 6, 4);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (26, '1.6 体检', 6, 5);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (27, '1.7 保险', 6, 6);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (28, '1.8 汇款', 6, 7);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (29, '1.9 Meal Plan', 6, 8);
/*Fill up Chapter 2 lvl 1*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (30, '2.0 说明', 7, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (31, '2.3 Double Major, Minor', 7, 3);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (32, '2.4 Overload', 7, 4);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (33, '2.5 GPA', 7, 5);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (34, '2.6 毕业要求', 7, 6);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (35, '2.9 Textbooks 教科书', 7, 9);
/*Fill up Chapter 2 lvl 2*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (36, '2.1.1 AE 航天工程', 12, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (37, '2.1.2 ME 机械工程', 12, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (38, '2.1.3 CH 化学', 12, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (39, '2.1.4 CHE 化学工程', 12, 3);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (40, '2.1.5 CS 计算机工程', 12, 4);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (41, '2.1.6 PH 物理', 12, 5);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (42, '2.1.7 MA 数学', 12, 6);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (43, '2.1.8 Actuarial 精算', 12, 7);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (44, '2.1.9 CE 土木工程', 12, 8);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (45, '2.1.10 AREN 建筑工程', 12, 9);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (46, '2.1.11 BUS 商学院', 12, 10);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (47, '2.1.12 ECE 电子工程', 12, 11);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (48, '2.1.13 RBE 机器人工程', 12, 12);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (49, '2.1.14 BB 生物和生物技术', 12, 13);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (50, '2.1.15 BME 生物医学工程', 12, 14);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (51, '2.1.16 BCB 生物信息处理', 12, 15);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (52, '2.1.17 Premedical 医学预科', 12, 16);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (53, '2.1.18 IMGD 游戏媒体', 12, 17);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (54, '2.1.19 ECON 经济', 12, 18);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (55, '2.1.20 Biochemistry 生物化学', 12, 19);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (56, '2.1.21 INTL 国际学', 12, 20);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (57, '2.1.22 WR 专业写作', 12, 21);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (58, '2.2.1 Requirements', 13, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (59, '2.2.2 German', 13, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (60, '2.2.3 Spanish', 13, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (61, '2.2.4 Music', 13, 3);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (62, '2.2.5 Arts', 13, 4);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (63, '2.2.6 History', 13, 5);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (64, '2.2.7 GPS', 13, 6);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (65, '2.7.1 Off Campus', 14, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (66, '2.7.2 On Campus', 14, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (67, '2.8.1 Chemistry Placement Test --REMOVED', 0, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (68, '2.8.1 AP转学分', 15, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (69, '2.8.2 SIE暑期学习转学分', 15, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (70, '2.8.3 其他', 15, 3);
/*Fill up Chapter 3*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (71, '3.1.1 社团活动', 16, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (72, '3.1.2 SNAP', 16, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (73, '3.1.3 Printer', 16, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (74, '3.2.1 手机', 17, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (75, '3.2.2 银行', 17, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (76, '3.2.3 购物', 17, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (77, '3.2.4 交通', 17, 3);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (78, '3.2.5 考驾照', 17, 4);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (79, '3.2.6 买车', 17, 5);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (80, '3.2.7 就医', 17, 6);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (81, '3.2.8 关于税', 17, 7);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (82, '3.2.9 其他活动', 17, 8);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (83, '3.3.1 校内居住', 18, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (84, '3.3.2 Break Contract', 18, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (85, '3.3.3 校外住宿', 18, 2);
/*Fill up Chapter 4*/
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (86, '4.1 校内工作', 9, 0);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (87, '4.2 校外工作', 9, 1);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (88, '4.3 校外工作许可 OPT & CPT', 9, 2);
INSERT INTO MENUS(ID, NAME, PARENT_ID, POSITION)VALUES (89, '4.4 Job Search', 9, 3);